### ISSUE TITLE
Implementation in UITableView Pull to Refresh

### ISSUE THREAD

**Issue by cohen72** [misterwell/MMMaterialDesignSpinner#11]
Would love to see functionality to allow using in UITableView for Pull to Refresh where the circle would gradually fill up or unfill according to the user's panning, and upon release would continue normal animation. 
Love your work!
Thanks :+1:

**Comment by misterwell** [comment]
Thanks! I'll look into this soon, I agree it would be awesome!

**Comment by misterwell** [comment]
I believe I've implemented enough support for this, and will be working to release it in 0.2.5 later today.
