### ISSUE TITLE
stop user interaction is not available 

### ISSUE THREAD

**Issue by kishoremobello** [misterwell/MMMaterialDesignSpinner#13]
while loading i am able to do interaction with parent view so stop user interaction

**Comment by misterwell** [comment]
I can't infer from your description what expected behavior you're looking for is. Please provide more details and I'll look into whether this should be fixed in the library.

**Comment by alejandroivan** [comment]
@kishoremobello that is not a task this library should handle. This spinner should work just like `UIActivityIndicatorView`.

To disable user interaction, you should do it in your view controller, just before `startAnimating` of this library. To re-enable it, do it just after `stopAnimating`.

**Comment by kishoremobello** [comment]
ok i understood but while loading the spinner if we stop user interaction then it will be grate library
