### ISSUE TITLE
Method possibly missing a [super awakeFromNib] call

### ISSUE THREAD

**Issue by pittNearsoft** [misterwell/MMMaterialDesignSpinner#16]
Hi,

This warning appears in Xcode 8.3 and swift 3.1

**Comment by iMark21** [comment]
Same problem here!

**Comment by misterwell** [comment]
Apologies for the radio silence guys, life got kind of crazy recently.

Feel free to issue a PR with a fix and I'll work to incorporate it as soon as possible with the other pending PRs.

**Comment by misterwell** [comment]
Scratch that, this was fixed by @Panajev!
